version: '3.3'

services:

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ${IMAGE:-app}
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_SERVICE_HOST=mongo
      - MONGO_SERVICE_PORT=27017
      - MONGO_DB=piplifetest      

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
