version: '3.3'

services:
  test:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.test
    image: ${IMAGE:-pip/test}
    depends_on:
      - mongo
    environment:
      - MONGO_SERVICE_HOST=mongo
      - MONGO_SERVICE_PORT=27017
      - MONGO_DB=piplifetest      

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"