---
# Container info
- descriptor: "pip-services:container-info:default:default:*"
  name: "pip-facades-example"
  description: "Example Pip.Services facade"

# Console logger
- descriptor: "pip-services:logger:console:default:1.0"
  level: "trace"

# Log counters
- descriptor: "pip-services:counters:log:default:*"

# {{^if MONGO_ENABLED}}{{^if FILE_ENABLED}}
# # Memory persistence
# - descriptor: "beacons:persistence:memory:default:1.0"
# {{/if}}{{/if}}

# {{^if MONGO_ENABLED}}
# # MongoDb persistence
# - descriptor: "beacons:persistence:mongodb:default:1.0"
#   connection:
#     uri: {{MONGO_SERVICE_URI}}
#     host: {{MONGO_SERVICE_HOST}}{{^if MONGO_SERVICE_HOST}}"localhost"{{/if}}
#     port: {{MONGO_SERVICE_PORT}}{{^if MONGO_SERVICE_PORT}}27017{{/if}}
#     database: {{MONGO_DB}}{{^if MONGO_DB}}"test"{{/if}}
# {{/if}}

{{^if FILE_ENABLED}}
# File persistence
- descriptor: "beacons:persistence:file:default:1.0"
  path: {{FILE_PATH}}{{^if FILE_PATH}}"../data/beacons.json"{{/if}}
{{/if}}

# Controller
- descriptor: "beacons:controller:default:default:1.0"

# Main facade service
- descriptor: "pip-services:endpoint:http:default:*"
  root_path: ""
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: 8080
  options:
    debug: true
    maintenance_enabled: false
    max_req_size: "1mb"

# Facade API V1
# - descriptor: "pip-facades-example:service:http:default:1.0"

# Hearbeat service
- descriptor: "pip-services:heartbeat-service:http:default:1.0"

# Status service
- descriptor: "pip-services:status-service:http:default:1.0"
